#!/bin/bash
source ./devel/setup.bash
export HUSKY_LMS1XX_ENABLED=1
echo "HUSKY_LMS1XX_ENABLED"

# HUSKY_LMS1XX_ENABLED=1
# HUSKY_LMS1XX_SECONDARY_ENABLED=1
# HUSKY_UST10_ENABLED=1
# HUSKY_UST10_SECONDARY_ENABLED=1
# HUSKY_LASER_3D_ENABLED=1              
# HUSKY_REALSENSE_ENABLED=1
# HUSKY_FRONT_BUMPER_EXTEND
# HUSKY_REAR_BUMPER_EXTEND
# HUSKY_URDF_EXTRAS